config/routes.rb
Rails.application.routes.draw do

  root 'sessions#login'
  get '/login', to: "sessions#login", as: 'login'
  get '/signup', to: "sessions#signup", as: 'signup'
  post '/login', to: "sessions#attempt_login"
  post '/signup', to: "sessions#create"
  delete '/logout', to: "sessions#logout", as: "logout"

  resources :teams do
    resources :superheros, shallow: true
  end

  resources :users

end

app/models/superhero.rb
class Superhero < ActiveRecord::Base
  belongs_to :team

  validates :name, :bio, :image_url, presence: true

end

app/models/team.rb
class Team < ActiveRecord::Base
  has_many :superheros, dependent: :destroy
  validates :name, uniqueness: {case_sensitive: false}, presence: true
  validates :description, presence: true, length: { maximum: 500, too_long: "%{count} characters is the maximum allowed" }
end

app/models/user.rb
class User < ActiveRecord::Base
  has_secure_password
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  def confirm_logged_in
    unless session[:user_id]
      redirect_to login_path, alert: "Please log in"
    end
  end

  # Stop a logged in user from going to the sign up page
  def prevent_login_signup
    if session[:user_id]
      redirect_to :back, notice: "You are already logged in"
      # what do you think redirect_to :back does?
    end
  end

  def current_user
  # Let's not make a database query if we don't need to!
   return unless session[:user_id]
  # Defines @current_user if it is not already defined.
   @current_user ||= User.find_by_id(session[:user_id])
  end
  helper_method :current_user #make it available in views (it will be available in all controllers as well
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def login
  end

  def signup
    @user = User.new
  end

  def create
    @user = User.create user_params
    if @user.save
      session[:user_id] = @user.id
      redirect_to teams_path
    else
      render :signup
    end
  end

  def attempt_login
    if params[:username].present? && params[:password].present?
      found_user = User.where(username: params[:username]).first
      if found_user && found_user.authenticate(params[:password])
        session[:user_id] = found_user.id
        redirect_to teams_path
      else
        flash[:alert] = "username / password combination is invalid"
        redirect_to login_path
      end
    else
      flash[:alert] = "please enter username and password"
      redirect_to login_path
    end
  end

  def logout
    # session.clear
    session[:user_id] = nil
    flash[:notice] = "Logged out"
    redirect_to login_path
  end

  private

  def user_params
    params.require(:user).permit(
      :username,
      :password,
      :avatar_url
    )
  end
end

app/controllers/superheros_controller.rb
class SuperherosController < ApplicationController
  before_action :set_team, only: [:index, :new, :create,]
  before_action :set_superhero, only: [:show, :edit, :update, :destroy]

  def index
    @superheros = @team.superheros
  end

  def new
    @superhero = Superhero.new
  end

  def create
    @superhero = @team.superheros.create superhero_params
    if @superhero.save
      redirect_to team_superheros_path(@team), flash: {success: "#{@superhero.name} added!"}
    else
      render :new
    end
  end

  def show
  end

  def edit
  end

  def update
    @superhero.update superhero_params
    if @superhero.save
      redirect_to superhero_path(@superhero), flash: {success: "#{@superhero.name} updated!"}
    else
      render :edit
    end
  end

  def destroy
    @superhero.destroy
    redirect_to teams_path, flash: {success: "#{@superhero.name} was successfully deleted"}
  end

  private

  def set_team
    @team = Team.find_by_id params[:team_id]
  end

  def set_superhero
    @superhero = Superhero.find params[:id]
  end

  def superhero_params
    params.require(:superhero).permit(
      :name,
      :bio,
      :height,
      :image_url,
      :team_id
    )
  end
end

app/controllers/teams_controller.rb
class TeamsController < ApplicationController
  before_action :set_team, only: [:show, :edit, :update, :destroy]
  before_action :confirm_logged_in, except: [:index]

  def index
    @teams = Team.all
  end

  def new
    @team = Team.new
  end

  def create
    @team = Team.create team_params
    if @team.save
      redirect_to teams_path, flash: {success: "#{@team.name} added!"}
    else
      render :new
    end
  end

  def edit
  end

  def update
    @team.update team_params
    if @team.save
      redirect_to team_path, flash: {success: "#{@team.name} updated!"}
    else
      render :edit
    end
  end

  def show
  end

  def destroy
    @team.destroy
    redirect_to teams_path, flash: {success: "#{@team.name} was successfully deleted"}
  end

  private

  def set_team
    @team = Team.find params[:id]
  end

  def team_params
    params.require(:team).permit(
      :name,
      :description
    )
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/superheros_helper.rb
module SuperherosHelper
end

app/helpers/teams_helper.rb
module TeamsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>TitanicTeams</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <nav id="mainNav" class="navbar navbar-default">
    <div class="container-fluid">
      <div class="navbar-header">
        <%= link_to "TITANIC TEAMS", root_path, class:"navbar-brand" %>
      </div>

      <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
        <ul class="nav navbar-nav">
          <li><%= link_to "Teams", teams_path %></li>
        </ul>
        <ul class="nav navbar-nav navbar-right">
          <% if current_user %>
            <li class="navbar-text">hello <%= current_user.username %></li>
            <li><%= link_to "Sign Out", logout_path, method: :delete %></li>
          <% else %>
            <li><%= link_to "SignIn", login_path %></li>
          <% end %>
        </ul>
      </div>
    </div>
  </nav>
  <div class="main container">
    <% flash.each do |key, value| %>
    <% if key == "notice" %>
      <%= content_tag :div, value, class: "text-center alert alert-warning" %>
    <% elsif key == "alert" %>
      <%= content_tag :div, value, class: "text-center alert alert-danger" %>
    <% else %>
      <%= content_tag :div, value, class: "text-center alert alert-success" %>
    <% end %>
<% end %>
    <%= yield %>
  </div>
</body>
</html>

app/views/shared/_errors.html.erb
<% if instance.errors.any? %>
  <div id="error_explanation" class="alert alert-danger">
    <h2><%= pluralize(instance.errors.count, "error") %> prohibited this <%= instance.class %> from being saved:</h2>
    <ul>
      <% instance.errors.full_messages.each do |message| %>
      <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/superheros/_form.html.erb
<%= form_for [@team, @superhero], html:{class: "form-horizontal"} do |f| %>
  <%= render partial: "shared/errors", locals: {instance: @superhero} %>
  <div class="well bs-component">
    <fieldset>
      <div class="form-group">
        <%= f.label :name, class:"col-sm-2 control-label"%>
        <div class="col-sm-8">
          <%= f.text_field :name, class:"form-control" %>
        </div>
      </div>
      <div class="form-group">
        <%= f.label :image_url, class:"col-sm-2 control-label"%>
        <div class="col-sm-8">
          <%= f.text_field :image_url, class:"form-control" %>
        </div>
      </div>
      <div class="form-group">
        <%= f.label :height, class:"col-sm-2 control-label"%>
        <div class="col-sm-8">
          <%= f.number_field :height, step:"0.01", class:"form-control", placeholder: "ft"%>
        </div>
      </div>
      <div class="form-group">
        <%= f.label :bio, class:"col-sm-2 control-label"%>
        <div class="col-sm-8">
          <%= f.text_area :bio, class:"form-control" %>
        </div>
      </div>
      <div class="form-group">
        <div class="col-sm-10 col-sm-offset-2">
          <%= f.submit class:"btn btn-primary" %>
          <% if params[:action] == "new" %>
            <%= link_to "Cancel", teams_path, class:"btn btn-default" %>
          <% end %>
        </div>
      </div>
    </fieldset>
  </div>
<% end %>

app/views/superheros/edit.html.erb
<h1 class="page-header">Edit <%= @superhero.name %></h1>
<%= render 'form' %>

app/views/superheros/index.html.erb
<%= link_to "Add Superheroes", new_team_superhero_path(@team), class:"btn btn-primary"%>

<h1 class="page-header"><%= "Superheroes for #{@team.name}" %></h1>
<div class="container-fluid">
  <div class="row">
  <% @superheros.each do |superhero| %>
    <div class="col-sm-3">
      <div class="thumbnail">
        <%= image_tag(superhero.image_url) %>
        <div class="caption">
          <h3><%= superhero.name %></h3>
          <p><%= link_to "Show", superhero_path(superhero), class:"btn btn-primary" %></p>
        </div>
      </div>
    </div>
  <% end %>
  </div>
</div>

app/views/superheros/new.html.erb
<h1 class="page-header">Add Superheroes</h1>

<%= render 'form' %>

app/views/superheros/show.html.erb
<h1 class="page-header"><i class="fa fa-bolt"></i> <%= @superhero.name %></h1>

<div class="team-profile container">
  <ul class="list-unstyled well">
    <li><%= image_tag(@superhero.image_url, class:"thumbnail profile-img") %></li>
    <li><p>Bio: <%= @superhero.bio %></p></li>
    <li><p>Height: <%= @superhero.height %></p></li>
    <li><p>Team: <%= @superhero.team.name %></p></li>
  </ul>
</div>
<div class="links">
  <%= link_to "Edit", edit_superhero_path(@superhero), class:"btn btn-info" %>
  <%= link_to "Delete", @superhero, method: :delete, data: {alert: "Are you sure?"},  class:"btn btn-warning" %>
</div>